version: "3"

services:
  blockory-front:
    container_name: blockory-front
    image: node:17-alpine
    volumes:
      - ./blockory:/usr/src/app
      - node_modules_volume:/usr/src/app/node_modules
    working_dir: /usr/src/app
    command: sh -c "yarn install && yarn start"
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true

volumes:
  node_modules_volume:
